import { v4 as uuidv4 } from "uuid";
import {
  covidAssets,
  devConnectorAssets,
  ecommerceAssets,
  chatAssets,
  ppmToolAssets,
  materialAssets,
  flowerStoreAssets,
} from "../utils/assets";

console.log(
  covidAssets,
  devConnectorAssets,
  ecommerceAssets,
  chatAssets,
  ppmToolAssets,
  materialAssets,
  flowerStoreAssets
);

console.log(covidAssets["covidTrackerThumb.png"]);

export const projects = [
  {
    id: uuidv4(),
    title: "E-Commerce Project",
    demoLink: "https://ecommerce-store-live.herokuapp.com/",
    thumbnail: ecommerceAssets["mainPage.png"].default,
    nestedShortSummary: false,
    shortSummary: "This demo is a sample e-commerce application.",
    nestedLongSummary: true,
    longSummary: [
      "Lets users purchase items using Stripe API, whether logged in or not.",
      "Lets users log in using Google OAuth.",
      "Lets users register and sign in with the credentials made.",
      "Utilizes Redux to manage state throughout the application.",
      "Utilizes Redux-Thunk and Redux-Saga to handle application side effects (for example, data fetching)",
      "Utilizes React-Persist to persist the shopping cart data, so when the user refreshes the page, the items in the cart remain.",
    ],
    images: [],
    tags: [
      "React",
      "Redux",
      "Firebase",
      "Redux-Persist",
      "Redux-Thunk",
      "Redux-Saga",
      "Reselect",
      "Styled-Components",
      "Express",
      "Stripe (Client and Server)",
    ],
    githubLink: "",
  },
  {
    id: uuidv4(),
    title: "MERN DevConnector Project",
    demoLink: "http://mernproject-devconnector.herokuapp.com/",
    thumbnail: devConnectorAssets["devConnectorThumb.png"].default,
    nestedShortSummary: false,
    shortSummary:
      "This demo is a networking tool that enables users to connect with other developers.",
    nestedLongSummary: false,
    longSummary: "",
    images: [],
    tags: [
      "React",
      "Redux",
      "Redux-Thunk",
      "Redux-Persist",
      "Mongo",
      "Express",
      "Node.js",
    ],
    githubLink: "",
  },
  {
    id: uuidv4(),
    title: "PPM Tool",
    demoLink: "https://ppmt-react-spring.herokuapp.com/",
    thumbnail: ppmToolAssets["ppmThumbnail.png"].default,
    nestedShortSummary: false,
    shortSummary:
      "This demo is a personal project tool that lets you keep track of your projects and tasks.",
    nestedLongSummary: false,
    longSummary:
      "This is a project management tool built with Spring Boot, MySQL, React, Redux, and Redux-Thunk.",
    images: [],
    tags: ["React", "Redux", "Redux-Thunk"],
    githubLink: "",
  },
  {
    id: uuidv4(),
    title: "Covid Tracker",
    demoLink: "",
    thumbnail: covidAssets["covidTrackerThumb.png"].default,
    nestedShortSummary: false,
    shortSummary:
      "This demo lets users view all the COVID-19 cases around the world.",
    nestedLongSummary: false,
    longSummary: "",
    images: [],
    tags: ["React", "ChartJS"],
    githubLink: "",
  },
  {
    id: uuidv4(),
    title: "Socket Chat",
    demoLink: "",
    thumbnail: chatAssets["socketChatThumb.png"].default,
    nestedShortSummary: false,
    shortSummary: "This demo is a chat system implemented by socket.io.",
    nestedLongSummary: false,
    longSummary: "",
    images: [],
    tags: ["React", "Express", "socket.io-client", "socket.io"],
    githubLink: "",
  },
  {
    id: uuidv4(),
    title: "Flower Store",
    demoLink: "",
    thumbnail: flowerStoreAssets["storeThumb.png"].default,
    nestedShortSummary: true,
    shortSummary: [{ store: "" }, { admin: "" }],
    nestedLongSummary: true,
    longSummary: [{ store: "" }, { admin: "" }],
    images: [],
    tags: [
      "Spring Boot",
      "Spring Security",
      "JPA",
      "Thymeleaf",
      "JavaMail",
      "Hibernate",
    ],
    githubLink: "",
  },
  {
    id: uuidv4(),
    title: "Material UI",
    demoLink: "",
    thumbnail: materialAssets["materialuiThumb.png"].default,
    shortSummary: "",
    nestedShortSummary: false,
    nestedLongSummary: false,
    longSummary: "",
    images: [],
    tags: ["React", "Material-UI", "Axios", "clsx", "Node Mailer"],
    githubLink: "https://github.com/danielbyun/material-ui/",
  },
];
