export const projects = [
  {
    id: 0,
    title: "E-Commerce Project",
    link: "https://ecommerce-store-live.herokuapp.com/",
    thumbnail: "",
    shortSummary: "",
    longSummary: "",
  },
  {
    id: 1,
    title: "MERN DevConnector Project",
    link: "http://mernproject-devconnector.herokuapp.com/",
    thumbnail: "",
    shortSummary: "",
    longSummary: "",
  },
  {
    id: 2,
    title: "PPM Tool",
    link: "https://ppmt-react-spring.herokuapp.com/",
    thumbnail: "",
    shortSummary: "",
    longSummary: "",
  },
  {
    id: 3,
    title: "Covid Tracker",
    link: "",
    thumbnail: "",
    shortSummary: "",
    longSummary: "",
  },
  {
    id: 4,
    title: "Socket Chat",
    link: "",
    thumbnail: "",
    shortSummary: "",
    longSummary: "",
  },
  {
    id: 5,
    title: "Flower Store",
    link: "",
    thumbnail: "",
    shortSummary: "",
    longSummary: "",
  },
];
